--
-- PostgreSQL database dump
--

\restrict lGXHAFZ6U9Wk3zWhtz10qINyrdmXTLfze4c5iDyih0FzL8dvAPdP3Bnrsn3gPwA

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

-- Started on 2026-08-24 23:11:38

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 17772)
-- Name: admins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admins (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(150) NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT admins_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying, 'OFFICER'::character varying])::text[])))
);


ALTER TABLE public.admins OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 17771)
-- Name: admins_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 18134)
-- Name: asset_usages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asset_usages (
    id bigint NOT NULL,
    cartridge_name character varying(150),
    colour character varying(30),
    created_at timestamp(6) without time zone NOT NULL,
    department character varying(100) NOT NULL,
    employee_id character varying(50) NOT NULL,
    employee_name character varying(100) NOT NULL,
    location character varying(100) NOT NULL,
    part_number character varying(100),
    printer_model character varying(150),
    printer_type character varying(30) NOT NULL,
    quantity_used integer NOT NULL,
    remarks character varying(1000),
    seat_or_cabin_no character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone,
    usage_date date NOT NULL,
    work_order_reference character varying(100),
    asset_id bigint,
    cartridge_id bigint NOT NULL,
    user_id bigint NOT NULL,
    recorded_by_employee_name character varying(100),
    recorded_by_employee_no character varying(50),
    beneficiary_employee_no character varying(50),
    beneficiary_employee_name character varying(100),
    beneficiary_department character varying(100),
    beneficiary_seat_or_cabin_no character varying(100),
    beneficiary_location character varying(100),
    beneficiary_email character varying(255),
    CONSTRAINT asset_usages_colour_check CHECK (((colour)::text = ANY ((ARRAY['BLACK'::character varying, 'CYAN'::character varying, 'MAGENTA'::character varying, 'YELLOW'::character varying])::text[]))),
    CONSTRAINT asset_usages_printer_type_check CHECK (((printer_type)::text = ANY ((ARRAY['BLACK_AND_WHITE'::character varying, 'COLOR'::character varying])::text[])))
);


ALTER TABLE public.asset_usages OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 18133)
-- Name: asset_usages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asset_usages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_usages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17923)
-- Name: assets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assets (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    department character varying(150) NOT NULL,
    model_name character varying(255) NOT NULL,
    printer_type character varying(30) NOT NULL,
    serial_number character varying(100) NOT NULL,
    status character varying(30) DEFAULT 'ACTIVE'::character varying NOT NULL,
    updated_at timestamp(6) without time zone,
    cartridge_id bigint NOT NULL,
    colour character varying(30),
    CONSTRAINT assets_colour_check CHECK (((colour)::text = ANY ((ARRAY['BLACK'::character varying, 'CYAN'::character varying, 'MAGENTA'::character varying, 'YELLOW'::character varying])::text[]))),
    CONSTRAINT assets_printer_type_check CHECK (((printer_type)::text = ANY ((ARRAY['BLACK_AND_WHITE'::character varying, 'COLOR'::character varying])::text[]))),
    CONSTRAINT assets_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'UNDER_MAINTENANCE'::character varying])::text[])))
);


ALTER TABLE public.assets OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17922)
-- Name: assets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 17783)
-- Name: call_up_purchase_orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.call_up_purchase_orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    po_date date NOT NULL,
    po_number character varying(255) NOT NULL,
    quantity integer NOT NULL,
    remarks character varying(1000),
    supplier_name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    rate_contract_id bigint NOT NULL
);


ALTER TABLE public.call_up_purchase_orders OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17782)
-- Name: call_up_purchase_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.call_up_purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.call_up_purchase_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17819)
-- Name: cartridge_thresholds; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cartridge_thresholds (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    po_threshold integer NOT NULL,
    updated_at timestamp(6) without time zone,
    cartridge_id bigint NOT NULL,
    tendering_threshold integer DEFAULT 10 NOT NULL
);


ALTER TABLE public.cartridge_thresholds OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17818)
-- Name: cartridge_thresholds_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cartridge_thresholds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cartridge_thresholds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17791)
-- Name: cartridges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cartridges (
    id bigint NOT NULL,
    active boolean NOT NULL,
    cartridge_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    number_of_printers integer NOT NULL,
    part_number character varying(255) NOT NULL,
    printer_name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    store_quantity integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.cartridges OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17790)
-- Name: cartridges_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cartridges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cartridges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 18519)
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    employee_number character varying(50) NOT NULL,
    full_name character varying(100) NOT NULL,
    email character varying(150),
    department character varying(100) NOT NULL,
    designation character varying(100),
    gd character varying(50),
    cabin_number character varying(100),
    seat_number character varying(50),
    location character varying(100),
    printer_name character varying(150),
    printer_serial_number character varying(100),
    printer_type character varying(50),
    status character varying(30) DEFAULT 'ACTIVE'::character varying NOT NULL,
    remarks character varying(1000),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 18518)
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.employees_id_seq OWNER TO postgres;

--
-- TOC entry 5024 (class 0 OID 0)
-- Dependencies: 233
-- Name: employees_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.employees_id_seq OWNED BY public.employees.id;


--
-- TOC entry 226 (class 1259 OID 17825)
-- Name: procurement_alerts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.procurement_alerts (
    id bigint NOT NULL,
    alert_type character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(1000) NOT NULL,
    net_available_quantity integer NOT NULL,
    resolved_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    threshold integer NOT NULL,
    cartridge_id bigint NOT NULL,
    email_failure_reason character varying(500),
    email_sent_at timestamp(6) without time zone,
    email_sent boolean DEFAULT false NOT NULL,
    combined_net_available_quantity integer,
    rate_contract_net_available_quantity integer,
    store_net_available_quantity integer,
    tendering_threshold integer,
    severity character varying(20) DEFAULT 'NORMAL'::character varying NOT NULL,
    CONSTRAINT procurement_alerts_alert_type_check CHECK (((alert_type)::text = ANY ((ARRAY['PROCUREMENT_THRESHOLD'::character varying, 'TENDERING_REQUIRED'::character varying])::text[]))),
    CONSTRAINT procurement_alerts_severity_check CHECK (((severity)::text = ANY ((ARRAY['NORMAL'::character varying, 'URGENT'::character varying])::text[]))),
    CONSTRAINT procurement_alerts_status_check CHECK (((status)::text = ANY ((ARRAY['UNREAD'::character varying, 'READ'::character varying])::text[])))
);


ALTER TABLE public.procurement_alerts OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17824)
-- Name: procurement_alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.procurement_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.procurement_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17799)
-- Name: rate_contracts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rate_contracts (
    id bigint NOT NULL,
    contract_date date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    net_available_quantity integer NOT NULL,
    quantity_already_executed integer NOT NULL,
    quantity_taken_through_wo integer NOT NULL,
    rate_per_unit numeric(12,2) NOT NULL,
    supplier_name character varying(255) NOT NULL,
    tax_percentage numeric(5,2) NOT NULL,
    total_contract_quantity integer NOT NULL,
    updated_at timestamp(6) without time zone,
    cartridge_id bigint NOT NULL
);


ALTER TABLE public.rate_contracts OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17798)
-- Name: rate_contracts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rate_contracts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rate_contracts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 18088)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    department character varying(50),
    email character varying(150) NOT NULL,
    employee_id character varying(50) NOT NULL,
    full_name character varying(100) NOT NULL,
    location character varying(50),
    password character varying(255) NOT NULL,
    role character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(50) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying, 'OFFICER'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 18087)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4785 (class 2604 OID 18522)
-- Name: employees id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees ALTER COLUMN id SET DEFAULT nextval('public.employees_id_seq'::regclass);


--
-- TOC entry 5000 (class 0 OID 17772)
-- Dependencies: 216
-- Data for Name: admins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admins (id, created_at, email, name, password, role, updated_at) FROM stdin;
1	2026-08-12 15:57:44.895285	admin@iocl.co.in	IOCL Administrator	$2a$12$YwjHcaK95WImjZRHdcEUUuSXct7cy8iuLXaJnOVyc32naeAMuQQzu	ADMIN	2026-08-12 15:57:44.895285
\.


--
-- TOC entry 5016 (class 0 OID 18134)
-- Dependencies: 232
-- Data for Name: asset_usages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asset_usages (id, cartridge_name, colour, created_at, department, employee_id, employee_name, location, part_number, printer_model, printer_type, quantity_used, remarks, seat_or_cabin_no, updated_at, usage_date, work_order_reference, asset_id, cartridge_id, user_id, recorded_by_employee_name, recorded_by_employee_no, beneficiary_employee_no, beneficiary_employee_name, beneficiary_department, beneficiary_seat_or_cabin_no, beneficiary_location, beneficiary_email) FROM stdin;
8	Canon 070 Black	BLACK	2026-08-20 08:37:05.940085	Procurement	IOCL10025	Anjali Varshney	Refinery	070-BLK	HP port	COLOR	1	Test Option 1: Auto-filled from Employee Master	Cabin A-101	2026-08-20 08:37:05.940085	2026-08-20	WO-AUTOFILL-001	6	1	11	Saurabh Engineer	ENG2539	IOCL10025	Anjali Varshney	Procurement	Cabin A-101	Refinery	anjali.varshney@iocl.co.in
9	Canon 070 Black	BLACK	2026-08-20 08:37:11.578451	Operations	MANUAL-999	Sunil Contractor	Refinery	070-BLK	HP port	COLOR	2	Test Option 2: Manual Beneficiary Entry	Control Room Desk 4	2026-08-20 08:37:11.578451	2026-08-20	WO-MANUAL-002	6	1	11	Saurabh Engineer	ENG2539	MANUAL-999	Sunil Contractor	Operations	Control Room Desk 4	Refinery	sunil.contractor@external.iocl.co.in
10	HP 416X High Yield Yellow	\N	2026-08-20 08:39:05.709257	Operations	EMP001	Arun Sharma	Refinery	W2043X	porter	BLACK_AND_WHITE	90	\N	809	2026-08-20 08:39:05.709257	2026-08-20	WO087	3	9	2	Sagar Varshney	IOCL1005	EMP001	Arun Sharma	Operations	809	Refinery	anjalivarshney405@gmail.com
4	Canon 070 Black	BLACK	2026-08-20 07:38:24.542203	IT	EMP205	Anjali Varshney	Head Office	070-BLK	HP port	COLOR	1	Cartridge replaced for IT cabin printer	A-204	2026-08-20 07:38:24.542203	2026-08-20	WO-2026-AUG-TEST	6	1	5	Rahul Sharma	ENG101	EMP205	Anjali Varshney	IT	A-204	Head Office	amit.kumar@iocl.co.in
11	HP 508X High Yield Black	BLACK	2026-08-20 11:17:06.282489	Procurement	EMP205	Amit Kumar	Head Office	CF360X	samsung	COLOR	15	\N	A-201	2026-08-20 11:17:06.282489	2026-08-20	Wo09	4	10	2	Sagar Varshney	IOCL1005	EMP205	Amit Kumar	Procurement	A-201	Head Office	amit.kumar@iocl.co.in
12	HP 508X High Yield Black	BLACK	2026-08-20 11:22:15.811192	Operations	EMP001	Arun Sharma	Refinery	CF360X	Galaxy	COLOR	500	Replaced	308	2026-08-20 11:22:15.811192	2026-08-20	WO0987	7	10	2	Sagar Varshney	IOCL1005	EMP001	Arun Sharma	Operations	308	Refinery	arun.sharma@iocl.co.in
13	HP 508X High Yield Black	BLACK	2026-08-20 11:49:00.966713	Operations	EMP001	Arun Sharma	Refinery	CF360X	Galaxy	COLOR	92	\N	204	2026-08-20 11:49:00.966713	2026-08-20	WO087	7	10	2	Sagar Varshney	IOCL1005	EMP001	Arun Sharma	Operations	204	Refinery	anjalivarshney405@gmail.com
14	HP 410X High Yield Yellow	YELLOW	2026-08-20 13:11:57.618851	Engineering	ENG2539	Saurabh Engineer	Refinery	CF412X	HP port	COLOR	479	\N	892	2026-08-20 13:11:57.618851	2026-08-20	\N	6	16	2	Sagar Varshney	IOCL1005	ENG2539	Saurabh Engineer	Engineering	892	Refinery	eng_2539@iocl.co.in
15	HP 77X High Yield Black	\N	2026-08-20 14:33:47.486427	Procurement	EMP205	Amit Kumar	Head Office	CF277X	hp kit	BLACK_AND_WHITE	1000	\N	B-409	2026-08-20 14:33:47.486427	2026-08-20	WO765	5	18	2	Sagar Varshney	IOCL1005	EMP205	Amit Kumar	Procurement	B-409	Head Office	anjalivarshney405@gmail.com
16	Canon Cartridge 069 Yellow	YELLOW	2026-08-20 14:46:12.099824	Human Resources	EMP208	Kavita Nair	Regional Office	069-YEL	HP port	COLOR	200	Replaced	098	2026-08-20 14:46:12.099824	2026-08-20	WO098	6	5	2	Sagar Varshney	IOCL1005	EMP208	Kavita Nair	Human Resources	098	Regional Office	kavita.nair@iocl.co.in
17	HP 410X High Yield Cyan	CYAN	2026-08-20 16:11:49.187781	Procurement	IOCL10025	Anjali Varshney	Refinery	CF411X	samsung	COLOR	50	Its empty	901	2026-08-20 16:11:49.187781	2026-08-20	WO762	4	15	2	Sagar Varshney	IOCL1005	IOCL10025	Anjali Varshney	Procurement	901	Refinery	sagarvarshney904@gmail.com
18	HP 416X High Yield Cyan	\N	2026-08-20 22:40:51.502319	Operations	EMP001	Arun Sharma	Refinery	W2041X	New Model	BLACK_AND_WHITE	200	\N	9hgg	2026-08-20 22:40:51.502319	2026-08-20	WOe24	2	7	2	Sagar Varshney	IOCL1005	EMP001	Arun Sharma	Operations	9hgg	Refinery	arun.sharma@iocl.co.in
19	Canon Cartridge 069 Yellow	YELLOW	2026-08-21 13:15:53.460096	Information Systems	EMP201	Anjali Varshney	Head Office	069-YEL	PRINTER-HO-01	COLOR	1	Employee Master integration verification test	Cabin-401	2026-08-21 13:15:53.460096	2026-08-21	\N	\N	5	20	Dev Engineer	ENG555	EMP201	Anjali Varshney	Information Systems	Cabin-401	Head Office	anjali.varshney@iocl.co.in
20	HP 410X High Yield Yellow	YELLOW	2026-08-21 13:19:29.355283	Operations	IOCL145	Prashant	Refinery	CF412X	samsung	COLOR	1	\N	0976	2026-08-21 13:19:29.355283	2026-08-21	\N	4	16	2	Sagar Varshney	IOCL1005	IOCL145	Prashant	Operations	0976	Refinery	anjalivarshney8923@gmail.com
5	HP 416X High Yield Black	BLACK	2026-08-20 07:42:00.863872	Stores	IOCL1111	Anjali	Head Office	W2040X	HP port	COLOR	3	\N	A-402	2026-08-20 07:42:00.863872	2026-08-20	WO901	6	6	2	Sagar Varshney	IOCL1005	IOCL1111	Anjali	Stores	A-402	Head Office	\N
3	HP 416X High Yield Yellow	\N	2026-08-20 06:51:48.349187	IT	IOCL1005	Sagar Varshney	Depot	W2043X	porter	BLACK_AND_WHITE	1	\N	402	2026-08-20 06:51:48.349187	2026-08-20	\N	3	9	2	Sagar Varshney	IOCL1005	IOCL1005	Sagar Varshney	IT	402	Depot	sagarvarshney904@gmail.com
1	Canon 070 Black	\N	2026-08-19 12:14:41.323606	Operations	EMP001	Arun Sharma	Refinery	070-BLK	HP LaserJet Pro M404n	BLACK_AND_WHITE	1	Routine replacement	A-104	2026-08-19 12:14:41.323606	2026-08-19	\N	\N	1	3	Arun Sharma	EMP001	EMP001	Arun Sharma	Operations	A-104	Refinery	arun.sharma@iocl.co.in
2	Canon Cartridge 069 Cyan	CYAN	2026-08-19 12:14:42.122967	Finance	EMP002	Bhavna Patel	Head Office	069-CYN	Canon Color imageCLASS LBP622Cdw	COLOR	2	Finance department cyan replacement	C-305	2026-08-19 12:14:42.122967	2026-08-19	\N	\N	3	4	Bhavna Patel	EMP002	EMP002	Bhavna Patel	Finance	C-305	Head Office	bhavna.patel@iocl.co.in
6	HP 77X High Yield Black	\N	2026-08-20 07:58:02.192886	Stores	IOCL112	ABC	Head Office	CF277X	hp kit	BLACK_AND_WHITE	100	\N	401	2026-08-20 07:58:02.192886	2026-08-20	WO091	5	18	2	Sagar Varshney	IOCL1005	IOCL112	ABC	Stores	401	Head Office	sagarvarshney054@gmail.com
7	Canon 070 Black	BLACK	2026-08-20 08:26:55.41372	Finance	EMP301	Anjali Varshney	Head Office	070-BLK	HP port	COLOR	3	Routine cartridge change for financial reporting cabin	Cabin A-204	2026-08-20 08:26:55.41372	2026-08-20	WO-IOCL-2026-99	6	1	9	Rahul Sharma	ENG4328	EMP301	Anjali Varshney	Finance	Cabin A-204	Head Office	anjali.varshney@iocl.co.in
\.


--
-- TOC entry 5012 (class 0 OID 17923)
-- Dependencies: 228
-- Data for Name: assets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assets (id, created_at, department, model_name, printer_type, serial_number, status, updated_at, cartridge_id, colour) FROM stdin;
1	2026-08-17 14:31:15.908771	IT Department	HP Color LaserJet Pro M454dn	COLOR	VNB3K12345	ACTIVE	2026-08-18 15:58:00.456894	6	BLACK
4	2026-08-18 11:50:43.174248	Legal & Compliance	samsung	COLOR	0987767GHJ	ACTIVE	2026-08-18 15:58:00.461891	10	BLACK
2	2026-08-17 14:37:59.317239	Procurement Cell	New Model	BLACK_AND_WHITE	QWERTY1234	ACTIVE	2026-08-18 16:23:32.401272	14	\N
3	2026-08-18 11:47:20.096443	Marketing Division	porter	BLACK_AND_WHITE	9Q87WT7	ACTIVE	2026-08-18 16:23:32.406551	9	\N
5	2026-08-18 15:59:25.427106	Legal & Compliance	hp kit	BLACK_AND_WHITE	98HJ	ACTIVE	2026-08-18 16:23:32.406551	10	\N
6	2026-08-18 22:29:09.552273	Marketing Division	HP port	COLOR	987GVCN	ACTIVE	2026-08-18 22:29:24.900866	6	MAGENTA
7	2026-08-20 11:19:38.357776	Marketing Division	Galaxy	COLOR	09UHGS6	ACTIVE	2026-08-20 11:19:38.357776	10	MAGENTA
\.


--
-- TOC entry 5002 (class 0 OID 17783)
-- Dependencies: 218
-- Data for Name: call_up_purchase_orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.call_up_purchase_orders (id, created_at, po_date, po_number, quantity, remarks, supplier_name, updated_at, rate_contract_id) FROM stdin;
5	2026-08-13 16:14:39.603754	2026-08-13	WO/2026	20	Give	Anjali Varshney	2026-08-13 16:14:39.604754	5
6	2026-08-13 16:24:12.720447	2026-08-13	wo/7867	391	Provide	Sagar Varshney	2026-08-13 16:24:12.720447	6
7	2026-08-13 16:25:10.874223	2026-08-13	88789	59	Deliver	Sagar Varshney	2026-08-13 16:25:10.875223	6
8	2026-08-13 16:41:02.656654	2026-08-13	hhj987	50	jhjhbjh	Rajesh	2026-08-13 16:41:02.657659	7
10	2026-08-17 12:15:30.668216	2026-08-17	08768ghb	100	Need now	Raghav	2026-08-17 12:15:30.668216	9
11	2026-08-17 16:00:11.477073	2026-08-17	092nwjsn	100	do	Anjali Varshney	2026-08-17 16:00:11.477073	5
12	2026-08-18 12:07:16.315564	2026-08-18	76t7ggu	10		Anjali Varshney	2026-08-18 12:07:16.315564	5
13	2026-08-18 13:00:48.38135	2026-08-18	987897jkjb	3		Anjali Varshney	2026-08-18 13:00:48.38135	5
14	2026-08-18 13:01:35.784159	2026-08-18	8y87sgui	10		Sagar Varshney	2026-08-18 13:01:35.784159	6
15	2026-08-18 23:19:03.285947	2026-08-18	921jbjskn	10		Anjali Varshney	2026-08-18 23:19:03.285947	5
16	2026-08-20 07:03:33.232919	2026-08-20	987qw	100		XYZ	2026-08-20 07:03:33.232919	12
17	2026-08-20 12:17:23.505555	2026-08-20	WO0987	1000		Neeraj	2026-08-20 12:17:23.505555	14
18	2026-08-20 12:33:30.603089	2026-08-20	WO123	1000	Deliver at location	Ajay Devgn	2026-08-20 12:33:30.603089	15
19	2026-08-20 14:32:41.901864	2026-08-20	WO90	1000		Alia	2026-08-20 14:32:41.901864	17
20	2026-08-20 14:37:58.395209	2026-08-20	WO098	1000		Alia	2026-08-20 14:37:58.395209	17
21	2026-08-20 14:39:52.298957	2026-08-20	WO765	1000	Need	Ranbir	2026-08-20 14:39:52.298957	18
22	2026-08-20 16:09:27.823134	2026-08-20	WO09871	100	po call	Rohan	2026-08-20 16:09:27.823134	21
23	2026-08-20 22:39:40.918838	2026-08-20	WO173	100		Shyam	2026-08-20 22:39:40.918838	22
24	2026-08-20 22:40:02.521526	2026-08-20	WO373	200		Ram	2026-08-20 22:40:02.521526	23
\.


--
-- TOC entry 5008 (class 0 OID 17819)
-- Dependencies: 224
-- Data for Name: cartridge_thresholds; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cartridge_thresholds (id, created_at, po_threshold, updated_at, cartridge_id, tendering_threshold) FROM stdin;
5	2026-08-14 00:12:21.066725	6	2026-08-14 00:12:21.066725	5	10
7	2026-08-14 00:12:21.073726	1	2026-08-14 00:12:21.073726	7	10
8	2026-08-14 00:12:21.077724	1	2026-08-14 00:12:21.077724	8	10
9	2026-08-14 00:12:21.080719	1	2026-08-14 00:12:21.080719	9	10
10	2026-08-14 00:12:21.083723	1	2026-08-14 00:12:21.083723	10	10
13	2026-08-14 00:12:21.092726	1	2026-08-14 00:12:21.092726	13	10
14	2026-08-14 00:12:21.096419	4	2026-08-14 00:12:21.096419	14	10
15	2026-08-14 00:12:21.099429	4	2026-08-14 00:12:21.099429	15	10
17	2026-08-14 00:12:21.105608	4	2026-08-14 00:12:21.105608	17	10
3	2026-08-14 00:12:21.057494	5656	2026-08-22 20:16:09.766332	3	10
4	2026-08-14 00:12:21.062826	10	2026-08-22 20:17:11.531139	4	10
1	2026-08-14 00:12:21.027188	6768786	2026-08-22 20:28:44.946238	1	50
6	2026-08-14 00:12:21.070727	1	2026-08-17 12:11:33.992433	6	200
12	2026-08-14 00:12:21.089718	1	2026-08-22 20:33:02.142398	12	11
2	2026-08-14 00:12:21.052489	55	2026-08-24 22:40:33.756141	2	25
18	2026-08-14 00:12:21.108613	100	2026-08-17 16:29:47.308397	18	500
11	2026-08-14 00:12:21.085728	1	2026-08-20 06:54:21.730805	11	10
16	2026-08-14 00:12:21.102419	4	2026-08-20 13:20:05.751362	16	10
\.


--
-- TOC entry 5004 (class 0 OID 17791)
-- Dependencies: 220
-- Data for Name: cartridges; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cartridges (id, active, cartridge_name, created_at, number_of_printers, part_number, printer_name, updated_at, store_quantity) FROM stdin;
1	t	Canon 070 Black	2026-08-13 15:42:02.117092	45	070-BLK	Canon LBP246dw	2026-08-13 15:42:02.117092	0
2	t	Canon Cartridge 069 Black	2026-08-13 15:42:02.155391	30	069-BLK	Canon LBP674Cx	2026-08-13 15:42:02.155391	0
3	t	Canon Cartridge 069 Cyan	2026-08-13 15:42:02.159391	30	069-CYN	Canon LBP674Cx	2026-08-13 15:42:02.159391	0
4	t	Canon Cartridge 069 Magenta	2026-08-13 15:42:02.161909	30	069-MAG	Canon LBP674Cx	2026-08-13 15:42:02.161909	0
6	t	HP 416X High Yield Black	2026-08-13 15:42:02.168322	25	W2040X	HP Color LaserJet Pro M454dn	2026-08-13 15:42:02.168322	0
8	t	HP 416X High Yield Magenta	2026-08-13 15:42:02.174363	25	W2042X	HP Color LaserJet Pro M454dn	2026-08-13 15:42:02.174363	0
9	t	HP 416X High Yield Yellow	2026-08-13 15:42:02.177363	25	W2043X	HP Color LaserJet Pro M454dn	2026-08-13 15:42:02.177363	0
10	t	HP 508X High Yield Black	2026-08-13 15:42:02.179358	15	CF360X	HP Color LaserJet Enterprise M553	2026-08-13 15:42:02.179358	0
11	t	HP 508X High Yield Cyan	2026-08-13 15:42:02.181879	15	CF361X	HP Color LaserJet Enterprise M553	2026-08-13 15:42:02.181879	0
12	t	HP 508X High Yield Yellow	2026-08-13 15:42:02.184346	15	CF362X	HP Color LaserJet Enterprise M553	2026-08-13 15:42:02.184346	0
13	t	HP 508X High Yield Magenta	2026-08-13 15:42:02.186345	15	CF363X	HP Color LaserJet Enterprise M553	2026-08-13 15:42:02.186345	0
14	t	HP 410X High Yield Black	2026-08-13 15:42:02.190855	20	CE410X	HP LaserJet Pro 400	2026-08-13 15:42:02.190855	0
17	t	HP 410X High Yield Magenta	2026-08-13 15:42:02.199374	20	CF413X	HP LaserJet Pro 400	2026-08-13 15:42:02.199374	0
18	t	HP 77X High Yield Black	2026-08-13 15:42:02.200879	18	CF277X	HP LaserJet Enterprise M507	2026-08-20 14:37:58.400211	1000
15	t	HP 410X High Yield Cyan	2026-08-13 15:42:02.193375	20	CF411X	HP LaserJet Pro 400	2026-08-20 16:11:49.193779	50
7	t	HP 416X High Yield Cyan	2026-08-13 15:42:02.170825	25	W2041X	HP Color LaserJet Pro M454dn	2026-08-20 22:40:51.507375	100
5	t	Canon Cartridge 069 Yellow	2026-08-13 15:42:02.165808	30	069-YEL	Canon LBP674Cx	2026-08-21 13:15:53.469107	799
16	t	HP 410X High Yield Yellow	2026-08-13 15:42:02.196374	20	CF412X	HP LaserJet Pro 400	2026-08-21 13:19:29.363285	520
\.


--
-- TOC entry 5018 (class 0 OID 18519)
-- Dependencies: 234
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employees (id, employee_number, full_name, email, department, designation, gd, cabin_number, seat_number, location, printer_name, printer_serial_number, printer_type, status, remarks, created_at, updated_at) FROM stdin;
1	EMP001	Arun Sharma	arun.sharma@iocl.co.in	Operations	\N	\N	\N	\N	Refinery	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
2	EMP002	Bhavna Patel	bhavna.patel@iocl.co.in	Finance	\N	\N	\N	\N	Head Office	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
3	EMP202	Vikram Singh	vikram.singh@iocl.co.in	Operations	\N	\N	\N	\N	Refinery	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
4	EMP203	Priya Sharma	priya.sharma@iocl.co.in	Finance	\N	\N	\N	\N	Head Office	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
5	EMP204	Rajesh Patel	rajesh.patel@iocl.co.in	Maintenance	\N	\N	\N	\N	Terminal	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
6	EMP205	Amit Kumar	amit.kumar@iocl.co.in	Procurement	\N	\N	\N	\N	Head Office	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
7	EMP206	Sunita Rao	sunita.rao@iocl.co.in	Stores	\N	\N	\N	\N	Depot	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
8	EMP207	Manoj Tiwari	manoj.tiwari@iocl.co.in	Engineering	\N	\N	\N	\N	Refinery	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
9	EMP208	Kavita Nair	kavita.nair@iocl.co.in	Human Resources	\N	\N	\N	\N	Regional Office	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
10	ENG1001	Rahul Sharma	rahul.sharma@iocl.co.in	Engineering	\N	\N	\N	\N	Refinery	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
11	ENG101	Rahul Sharma	rahul.engineer@iocl.co.in	Engineering	\N	\N	\N	\N	Head Office	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
12	ENG2539	Saurabh Engineer	eng_2539@iocl.co.in	Engineering	\N	\N	\N	\N	Refinery	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
13	ENG4328	Rahul Sharma	engineer_4328@iocl.co.in	Engineering	\N	\N	\N	\N	Refinery	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
14	ENG4990	Rahul Sharma	engineer_4990@iocl.co.in	Engineering	\N	\N	\N	\N	Refinery	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
15	ENG5148	Rahul Sharma	engineer_5148@iocl.co.in	Engineering	\N	\N	\N	\N	Refinery	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
16	ENG5299	Pooja Verma	pooja_5299@iocl.co.in	Maintenance	\N	\N	\N	\N	Refinery	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
17	IOCL10025	Anjali Varshney	anjali.varshney@iocl.co.in	Procurement	\N	\N	\N	\N	Refinery	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
18	IOCL1005	Sagar Varshney	sagarvarshney904@gmail.com	IT	\N	\N	\N	\N	Depot	\N	\N	\N	ACTIVE	\N	2026-08-21 12:59:51.226421	2026-08-21 12:59:51.226421
19	EMP201	Anjali Varshney	anjali.varshney@iocl.co.in	Information Systems	Chief Manager (IS)	Grade F	Cabin-401	\N	Head Office	Canon LBP246dw	CN-SER-40101	Black & White	ACTIVE	\N	2026-08-21 13:04:48.700731	2026-08-21 13:04:48.700731
20	93917	Rajesh K. Sharma	rajesh.sharma@iocl.co.in	Information Systems	Manager (IS)	Grade F	Admin-505	\N	Refinery Complex	HP LaserJet M454dn	HP-SER-505	Black & White	INACTIVE	Promoted and updated cabin	2026-08-21 13:05:13.63546	2026-08-21 13:05:13.838995
21	TEST_98312	Rajesh Kumar	rajesh.kumar@iocl.co.in	Information Systems	Senior Engineer	Grade E	Cabin-412	\N	Refinery Complex	Canon LBP246dw	CN-SER-41289	Black & White	INACTIVE	Test creation from PowerShell	2026-08-21 13:05:59.740895	2026-08-21 13:06:00.019285
22	TEST_27519	Rajesh Kumar	rajesh.kumar@iocl.co.in	Information Systems	Senior Engineer	Grade E	Cabin-412	\N	Refinery Complex	Canon LBP246dw	CN-SER-41289	Black & White	INACTIVE	Test creation from PowerShell	2026-08-21 13:06:22.69942	2026-08-21 13:06:22.897921
23	TEST_14377	Rajesh K. Sharma	rajesh.sharma@iocl.co.in	Information Systems	Manager - IS	Grade F	Admin-505	\N	Refinery Complex	HP LaserJet M454dn	HP-SER-505	Black & White	INACTIVE	Promoted and updated cabin	2026-08-21 13:06:32.333698	2026-08-21 13:06:32.442038
24	IOCL_44299	Siddharth Malhotra	siddharth.m@iocl.co.in	Engineering Services	Senior Lead Engineer	Grade F	Admin-802	Desk 01	Head Office	HP LaserJet Enterprise M507x	HP-SER-80201	Black & White	INACTIVE	Promoted and transferred to Head Office	2026-08-21 13:14:08.741394	2026-08-21 13:14:08.985375
25	IOCL145	Prashant	anjalivarshney8923@gmail.com	Operations	Senior Engineer	k	208	12	Refinery	Canon	987CN	Color	INACTIVE		2026-08-21 13:18:31.844013	2026-08-21 14:46:40.890631
\.


--
-- TOC entry 5010 (class 0 OID 17825)
-- Dependencies: 226
-- Data for Name: procurement_alerts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.procurement_alerts (id, alert_type, created_at, message, net_available_quantity, resolved_at, status, threshold, cartridge_id, email_failure_reason, email_sent_at, email_sent, combined_net_available_quantity, rate_contract_net_available_quantity, store_net_available_quantity, tendering_threshold, severity) FROM stdin;
16	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.290452	Procurement Alert: HP 410X High Yield Magenta (CF413X) has 0 units remaining in the Rate Contract. PO threshold is 4.	0	2026-08-14 00:14:03.108105	READ	4	17	\N	\N	f	\N	\N	\N	\N	NORMAL
15	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.282452	Procurement Alert: HP 410X High Yield Yellow (CF412X) has 0 units remaining in the Rate Contract. PO threshold is 4.	0	2026-08-14 00:14:05.962946	READ	4	16	\N	\N	f	\N	\N	\N	\N	NORMAL
14	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.275452	Procurement Alert: HP 410X High Yield Cyan (CF411X) has 0 units remaining in the Rate Contract. PO threshold is 4.	0	2026-08-14 00:14:05.962946	READ	4	15	\N	\N	f	\N	\N	\N	\N	NORMAL
13	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.268455	Procurement Alert: HP 410X High Yield Black (CE410X) has 0 units remaining in the Rate Contract. PO threshold is 4.	0	2026-08-14 00:14:05.962946	READ	4	14	\N	\N	f	\N	\N	\N	\N	NORMAL
12	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.256352	Procurement Alert: HP 77X High Yield Black (CF277X) has 0 units remaining in the Rate Contract. PO threshold is 11.	0	2026-08-14 00:14:05.962946	READ	11	18	\N	\N	f	\N	\N	\N	\N	NORMAL
11	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.247607	Procurement Alert: HP 416X High Yield Yellow (W2043X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-14 00:14:05.962946	READ	1	9	\N	\N	f	\N	\N	\N	\N	NORMAL
10	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.238618	Procurement Alert: HP 416X High Yield Magenta (W2042X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-14 00:14:05.962946	READ	1	8	\N	\N	f	\N	\N	\N	\N	NORMAL
9	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.230617	Procurement Alert: HP 416X High Yield Cyan (W2041X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-14 00:14:05.962946	READ	1	7	\N	\N	f	\N	\N	\N	\N	NORMAL
8	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.213619	Procurement Alert: HP 508X High Yield Magenta (CF363X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-14 00:14:05.962946	READ	1	13	\N	\N	f	\N	\N	\N	\N	NORMAL
7	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.203235	Procurement Alert: HP 508X High Yield Yellow (CF362X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-14 00:14:05.962946	READ	1	12	\N	\N	f	\N	\N	\N	\N	NORMAL
6	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.195195	Procurement Alert: HP 508X High Yield Cyan (CF361X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-14 00:14:05.962946	READ	1	11	\N	\N	f	\N	\N	\N	\N	NORMAL
5	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.185193	Procurement Alert: HP 508X High Yield Black (CF360X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-14 00:14:05.962946	READ	1	10	\N	\N	f	\N	\N	\N	\N	NORMAL
4	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.175199	Procurement Alert: Canon Cartridge 069 Yellow (069-YEL) has 0 units remaining in the Rate Contract. PO threshold is 6.	0	2026-08-14 00:14:05.962946	READ	6	5	\N	\N	f	\N	\N	\N	\N	NORMAL
3	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.165299	Procurement Alert: Canon Cartridge 069 Magenta (069-MAG) has 0 units remaining in the Rate Contract. PO threshold is 6.	0	2026-08-14 00:14:05.962946	READ	6	4	\N	\N	f	\N	\N	\N	\N	NORMAL
2	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.152194	Procurement Alert: Canon Cartridge 069 Cyan (069-CYN) has 0 units remaining in the Rate Contract. PO threshold is 6.	0	2026-08-14 00:14:05.962946	READ	6	3	\N	\N	f	\N	\N	\N	\N	NORMAL
1	PROCUREMENT_THRESHOLD	2026-08-14 00:12:21.141195	Procurement Alert: Canon Cartridge 069 Black (069-BLK) has 0 units remaining in the Rate Contract. PO threshold is 6.	0	2026-08-14 00:14:05.962946	READ	6	2	\N	\N	f	\N	\N	\N	\N	NORMAL
33	PROCUREMENT_THRESHOLD	2026-08-14 22:43:04.287816	Procurement Alert: Canon 070 Black (070-BLK) has 860 units remaining in the Rate Contract. PO threshold is 861.	860	2026-08-14 22:50:57.214437	READ	861	1	Mail delivery failed: Authentication failed	\N	f	\N	\N	\N	\N	NORMAL
34	PROCUREMENT_THRESHOLD	2026-08-14 23:02:15.081831	Procurement Alert: Canon 070 Black (070-BLK) has 860 units remaining in the Rate Contract. PO threshold is 861.	860	2026-08-17 11:49:41.374527	READ	861	1	\N	2026-08-14 23:02:20.288895	t	\N	\N	\N	\N	NORMAL
31	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.637501	Procurement Alert: HP 410X High Yield Yellow (CF412X) has 0 units remaining in the Rate Contract. PO threshold is 4.	0	2026-08-18 07:16:16.003889	READ	4	16	\N	\N	f	\N	\N	\N	\N	NORMAL
28	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.569712	Procurement Alert: HP 77X High Yield Black (CF277X) has 0 units remaining in the Rate Contract. PO threshold is 0.	0	2026-08-17 12:12:17.173004	READ	0	18	\N	\N	f	\N	\N	\N	\N	NORMAL
30	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.615944	Procurement Alert: HP 410X High Yield Cyan (CF411X) has 0 units remaining in the Rate Contract. PO threshold is 4.	0	2026-08-18 07:16:17.922972	READ	4	15	\N	\N	f	\N	\N	\N	\N	NORMAL
29	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.592351	Procurement Alert: HP 410X High Yield Black (CE410X) has 0 units remaining in the Rate Contract. PO threshold is 4.	0	2026-08-18 07:16:18.625637	READ	4	14	\N	\N	f	\N	\N	\N	\N	NORMAL
27	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.551217	Procurement Alert: HP 416X High Yield Yellow (W2043X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-18 07:16:18.830527	READ	1	9	\N	\N	f	\N	\N	\N	\N	NORMAL
26	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.52753	Procurement Alert: HP 416X High Yield Magenta (W2042X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-18 07:16:18.996049	READ	1	8	\N	\N	f	\N	\N	\N	\N	NORMAL
25	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.509624	Procurement Alert: HP 416X High Yield Cyan (W2041X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-18 07:16:19.452987	READ	1	7	\N	\N	f	\N	\N	\N	\N	NORMAL
24	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.449052	Procurement Alert: HP 508X High Yield Magenta (CF363X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-18 07:16:19.633527	READ	1	13	\N	\N	f	\N	\N	\N	\N	NORMAL
23	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.425476	Procurement Alert: HP 508X High Yield Yellow (CF362X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-18 07:16:19.886669	READ	1	12	\N	\N	f	\N	\N	\N	\N	NORMAL
21	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.370873	Procurement Alert: HP 508X High Yield Black (CF360X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-18 07:16:20.19219	READ	1	10	\N	\N	f	\N	\N	\N	\N	NORMAL
20	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.337142	Procurement Alert: Canon Cartridge 069 Yellow (069-YEL) has 0 units remaining in the Rate Contract. PO threshold is 6.	0	2026-08-18 07:16:20.368135	READ	6	5	\N	\N	f	\N	\N	\N	\N	NORMAL
19	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.312761	Procurement Alert: Canon Cartridge 069 Magenta (069-MAG) has 0 units remaining in the Rate Contract. PO threshold is 6.	0	2026-08-18 07:16:20.521269	READ	6	4	\N	\N	f	\N	\N	\N	\N	NORMAL
18	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.174126	Procurement Alert: Canon Cartridge 069 Cyan (069-CYN) has 0 units remaining in the Rate Contract. PO threshold is 6.	0	2026-08-18 07:16:20.643979	READ	6	3	\N	\N	f	\N	\N	\N	\N	NORMAL
17	PROCUREMENT_THRESHOLD	2026-08-14 00:14:41.37087	Procurement Alert: Canon Cartridge 069 Black (069-BLK) has 0 units remaining in the Rate Contract. PO threshold is 5.	0	2026-08-18 07:16:22.410459	READ	5	2	\N	\N	f	\N	\N	\N	\N	NORMAL
32	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.668964	Procurement Alert: HP 410X High Yield Magenta (CF413X) has 0 units remaining in the Rate Contract. PO threshold is 4.	0	2026-08-18 07:22:19.291716	READ	4	17	\N	\N	f	\N	\N	\N	\N	NORMAL
41	TENDERING_REQUIRED	2026-08-17 08:04:18.252042	URGENT: Tendering required for cartridge Canon 070 Black (070-BLK). Store availability: 0, Rate contract availability: 860, Combined availability: 860. Tendering threshold: 870. Combined availability is below the tendering threshold.	860	2026-08-17 08:04:36.416787	READ	870	1	\N	2026-08-17 08:04:24.999369	t	860	860	0	870	URGENT
48	TENDERING_REQUIRED	2026-08-17 12:13:38.867626	URGENT: Tendering required for cartridge HP 77X High Yield Black (CF277X). Store availability: 0, Rate contract availability: 1000, Combined availability: 1000. Tendering threshold: 1200. Combined availability is below the tendering threshold.	1000	2026-08-17 12:14:11.113994	READ	1200	18	\N	2026-08-17 12:13:45.095175	t	1000	1000	0	1200	URGENT
43	PROCUREMENT_THRESHOLD	2026-08-17 11:46:55.38272	Procurement Alert: HP 416X High Yield Black (W2040X) has 173 units remaining in the Rate Contract. PO threshold is 176.	173	2026-08-17 11:49:32.152387	READ	176	6	Mail delivery failed: Mail server connection failed. Failed messages: jakarta.mail.MessagingException: Exception reading response;\n  nested exception is:\n\tjava.net.SocketTimeoutException: Read timed out	\N	f	\N	\N	\N	\N	NORMAL
42	TENDERING_REQUIRED	2026-08-17 11:32:52.791753	URGENT: Tendering required for cartridge Canon 070 Black (070-BLK). Store availability: 0, Rate contract availability: 860, Combined availability: 860. Tendering threshold: 861. Combined availability is below the tendering threshold.	860	2026-08-17 11:50:35.660079	READ	861	1	\N	2026-08-17 11:33:07.735036	t	860	860	0	861	URGENT
59	PROCUREMENT_THRESHOLD	2026-08-17 16:21:41.897083	Procurement Alert: HP 77X High Yield Black (CF277X) has 900 units remaining in the Rate Contract. PO threshold is 1000.	900	2026-08-17 16:29:47.338008	READ	1000	18	\N	2026-08-17 16:21:48.882625	t	\N	\N	\N	\N	NORMAL
49	PROCUREMENT_THRESHOLD	2026-08-17 13:08:41.171862	Procurement Alert: Canon 070 Black (070-BLK) has 860 units remaining in the Rate Contract. PO threshold is 1000.	860	2026-08-17 16:29:54.294051	READ	1000	1	\N	2026-08-17 13:08:49.841689	t	\N	\N	\N	\N	NORMAL
46	PROCUREMENT_THRESHOLD	2026-08-17 12:10:46.524385	Procurement Alert: Canon 070 Black (070-BLK) has 860 units remaining in the Rate Contract. PO threshold is 890.	860	2026-08-17 12:11:13.579013	READ	890	1	\N	2026-08-17 12:10:56.053845	t	\N	\N	\N	\N	NORMAL
45	TENDERING_REQUIRED	2026-08-17 11:52:05.055892	URGENT: Tendering required for cartridge HP 77X High Yield Black (CF277X). Store availability: 0, Rate contract availability: 0, Combined availability: 0. Tendering threshold: 10. Combined availability is below the tendering threshold.	0	2026-08-17 12:12:17.194881	READ	10	18	Tendering mail delivery failed: Mail server connection failed. Failed messages: jakarta.mail.MessagingException: Exception reading response;\n  nested exception is:\n\tjava.net.SocketTimeoutException: Read timed out	\N	f	0	0	0	10	URGENT
47	PROCUREMENT_THRESHOLD	2026-08-17 12:12:37.323453	Procurement Alert: HP 77X High Yield Black (CF277X) has 1000 units remaining in the Rate Contract. PO threshold is 1900.	1000	2026-08-17 12:13:25.766294	READ	1900	18	\N	2026-08-17 12:12:50.010909	t	\N	\N	\N	\N	NORMAL
50	TENDERING_REQUIRED	2026-08-17 13:09:39.371182	URGENT: Tendering required for cartridge Canon 070 Black (070-BLK). Store availability: 0, Rate contract availability: 860, Combined availability: 860. Tendering threshold: 900. Combined availability is below the tendering threshold.	860	2026-08-17 17:01:54.42856	READ	900	1	\N	2026-08-17 13:09:45.528288	t	860	860	0	900	URGENT
44	TENDERING_REQUIRED	2026-08-17 11:50:49.289912	URGENT: Tendering required for cartridge HP 416X High Yield Black (W2040X). Store availability: 0, Rate contract availability: 73, Combined availability: 73. Tendering threshold: 200. Combined availability is below the tendering threshold.	73	2026-08-17 17:01:55.77912	READ	200	6	Tendering mail delivery failed: Failed messages: jakarta.mail.MessagingException: Exception reading response;\n  nested exception is:\n\tjava.net.SocketTimeoutException: Read timed out	\N	f	73	73	0	200	URGENT
22	PROCUREMENT_THRESHOLD	2026-08-14 17:32:07.398637	Procurement Alert: HP 508X High Yield Cyan (CF361X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-18 07:16:20.066705	READ	1	11	\N	\N	f	\N	\N	\N	\N	NORMAL
70	TENDERING_REQUIRED	2026-08-18 23:19:03.492922	URGENT: Tendering required for cartridge HP 416X High Yield Black (W2040X). Store availability: 0, Rate contract availability: 47, Combined availability: 47. Tendering threshold: 200. Combined availability is below the tendering threshold.	47	2026-08-22 20:25:29.218295	READ	200	6	\N	2026-08-18 23:19:10.163007	t	47	47	0	200	URGENT
63	TENDERING_REQUIRED	2026-08-18 07:42:27.474784	URGENT: Tendering required for cartridge Canon Cartridge 069 Black (069-BLK). Store availability: 0, Rate contract availability: 0, Combined availability: 0. Tendering threshold: 10. Combined availability is below the tendering threshold.	0	2026-08-18 11:27:13.701674	READ	10	2	\N	2026-08-18 07:42:31.799364	t	0	0	0	10	URGENT
62	PROCUREMENT_THRESHOLD	2026-08-18 07:42:20.844504	Procurement Alert: Canon Cartridge 069 Black (069-BLK) has 0 units remaining in the Rate Contract. PO threshold is 50.	0	2026-08-18 11:27:13.701674	READ	50	2	\N	2026-08-18 07:42:27.412473	t	\N	\N	\N	\N	NORMAL
61	TENDERING_REQUIRED	2026-08-18 07:41:07.05058	URGENT: Tendering required for cartridge Canon 070 Black (070-BLK). Store availability: 0, Rate contract availability: 860, Combined availability: 860. Tendering threshold: 900. Combined availability is below the tendering threshold.	860	2026-08-18 11:27:13.701674	READ	900	1	\N	2026-08-18 07:41:12.095547	t	860	860	0	900	URGENT
60	PROCUREMENT_THRESHOLD	2026-08-18 07:40:54.483996	Procurement Alert: Canon 070 Black (070-BLK) has 860 units remaining in the Rate Contract. PO threshold is 900.	860	2026-08-18 11:27:13.701674	READ	900	1	\N	2026-08-18 07:41:07.03687	t	\N	\N	\N	\N	NORMAL
65	TENDERING_REQUIRED	2026-08-18 12:07:16.467466	URGENT: Tendering required for cartridge HP 416X High Yield Black (W2040X). Store availability: 0, Rate contract availability: 60, Combined availability: 60. Tendering threshold: 200. Combined availability is below the tendering threshold.	60	2026-08-18 13:21:36.268704	READ	200	6	Tendering mail delivery failed: Mail server connection failed. Failed messages: org.eclipse.angus.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 587; timeout 5000;\n  nested exception is:\n\tjava.net.UnknownHostException: smtp.gmail.com	\N	f	60	60	0	200	URGENT
64	PROCUREMENT_THRESHOLD	2026-08-18 11:37:51.321591	Procurement Alert: Canon 070 Black (070-BLK) has 850 units remaining in the Rate Contract. PO threshold is 900.	850	2026-08-20 07:03:03.023387	READ	900	1	Mail delivery failed: Failed messages: jakarta.mail.MessagingException: Exception reading response;\n  nested exception is:\n\tjava.net.SocketTimeoutException: Read timed out	\N	f	\N	\N	\N	\N	NORMAL
111	PROCUREMENT_THRESHOLD	2026-08-22 20:26:03.086481	Procurement Alert: Canon Cartridge 069 Black (069-BLK) has 21 units remaining in the Rate Contract. PO threshold is 55.	21	\N	UNREAD	55	2	\N	2026-08-22 20:26:08.106222	t	\N	\N	\N	\N	NORMAL
78	TENDERING_REQUIRED	2026-08-20 06:54:12.493064	URGENT: Tendering required for cartridge HP 508X High Yield Cyan (CF361X). Store availability: 0, Rate contract availability: 90, Combined availability: 90. Tendering threshold: 100. Combined availability is below the tendering threshold.	90	2026-08-20 06:54:21.751846	READ	100	11	\N	2026-08-20 06:54:17.193361	t	90	90	0	100	URGENT
83	PROCUREMENT_THRESHOLD	2026-08-20 11:17:06.427937	Procurement Alert: HP 508X High Yield Black (CF360X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-20 11:21:06.905263	READ	1	10	\N	2026-08-20 11:17:13.43608	t	\N	\N	\N	\N	NORMAL
84	TENDERING_REQUIRED	2026-08-20 11:17:13.471806	URGENT: Tendering required for cartridge HP 508X High Yield Black (CF360X). Store availability: 0, Rate contract availability: 0, Combined availability: 0. Tendering threshold: 10. Combined availability is below the tendering threshold.	0	2026-08-20 11:21:06.912374	READ	10	10	\N	2026-08-20 11:17:18.863291	t	0	0	0	10	URGENT
87	TENDERING_REQUIRED	2026-08-20 12:53:19.860339	URGENT: Tendering required for cartridge HP 410X High Yield Yellow (CF412X). Store availability: 521, Rate contract availability: 9000, Combined availability: 9521. Tendering threshold: 20000. Combined availability is below the tendering threshold.	9521	2026-08-20 13:20:05.760497	READ	20000	16	Tendering mail delivery failed: Failed messages: jakarta.mail.MessagingException: Exception reading response;\n  nested exception is:\n\tjava.net.SocketTimeoutException: Read timed out	\N	f	9521	9000	521	20000	URGENT
77	TENDERING_REQUIRED	2026-08-20 06:51:55.179325	URGENT: Tendering required for cartridge HP 416X High Yield Yellow (W2043X). Store availability: 0, Rate contract availability: 0, Combined availability: 0. Tendering threshold: 10. Combined availability is below the tendering threshold.	0	2026-08-21 14:44:07.845742	READ	10	9	\N	2026-08-20 06:51:59.703781	t	0	0	0	10	URGENT
76	PROCUREMENT_THRESHOLD	2026-08-20 06:51:48.453918	Procurement Alert: HP 416X High Yield Yellow (W2043X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	2026-08-22 20:08:44.887936	READ	1	9	\N	2026-08-20 06:51:55.139186	t	\N	\N	\N	\N	NORMAL
66	PROCUREMENT_THRESHOLD	2026-08-18 12:50:05.432819	Procurement Alert: Canon Cartridge 069 Black (069-BLK) has 21 units remaining in the Rate Contract. PO threshold is 66.	21	2026-08-22 20:16:41.133655	READ	66	2	Mail delivery failed: Mail server connection failed. Failed messages: jakarta.mail.MessagingException: Exception reading response;\n  nested exception is:\n\tjava.net.SocketTimeoutException: Read timed out	\N	f	\N	\N	\N	\N	NORMAL
104	PROCUREMENT_THRESHOLD	2026-08-22 20:10:46.836641	Procurement Alert: Canon 070 Black (070-BLK) has 1243 units remaining in the Rate Contract. PO threshold is 1243.	1243	2026-08-22 20:11:10.101936	READ	1243	1	\N	2026-08-22 20:10:53.756988	t	\N	\N	\N	\N	NORMAL
105	PROCUREMENT_THRESHOLD	2026-08-22 20:14:16.19473	Procurement Alert: Canon 070 Black (070-BLK) has 1243 units remaining in the Rate Contract. PO threshold is 6060.	1243	2026-08-22 20:14:50.721072	READ	6060	1	\N	2026-08-22 20:14:21.122131	t	\N	\N	\N	\N	NORMAL
112	PROCUREMENT_THRESHOLD	2026-08-22 20:28:44.953439	Procurement Alert: Canon 070 Black (070-BLK) has 1243 units remaining in the Rate Contract. PO threshold is 6768786.	1243	\N	UNREAD	6768786	1	\N	2026-08-22 20:28:49.842058	t	\N	\N	\N	\N	NORMAL
113	PROCUREMENT_THRESHOLD	2026-08-22 20:33:02.149904	Procurement Alert: HP 508X High Yield Yellow (CF362X) has 0 units remaining in the Rate Contract. PO threshold is 1.	0	\N	UNREAD	1	12	\N	2026-08-22 20:33:07.690724	t	\N	\N	\N	\N	NORMAL
109	PROCUREMENT_THRESHOLD	2026-08-22 20:18:26.112391	Procurement Alert: Canon Cartridge 069 Black (069-BLK) has 21 units remaining in the Rate Contract. PO threshold is 23.	21	2026-08-22 20:18:48.768389	READ	23	2	\N	2026-08-22 20:18:30.565907	t	\N	\N	\N	\N	NORMAL
108	PROCUREMENT_THRESHOLD	2026-08-22 20:17:10.274433	Procurement Alert: Canon Cartridge 069 Black (069-BLK) has 21 units remaining in the Rate Contract. PO threshold is 39.	21	2026-08-22 20:18:01.594375	READ	39	2	\N	2026-08-22 20:17:14.920658	t	\N	\N	\N	\N	NORMAL
114	TENDERING_REQUIRED	2026-08-22 20:33:07.699828	URGENT: Tendering required for cartridge HP 508X High Yield Yellow (CF362X). Store availability: 0, Rate contract availability: 0, Combined availability: 0. Tendering threshold: 11. Combined availability is below the tendering threshold.	0	\N	UNREAD	11	12	\N	2026-08-22 20:33:12.162491	t	0	0	0	11	URGENT
110	PROCUREMENT_THRESHOLD	2026-08-22 20:18:50.277899	Procurement Alert: Canon Cartridge 069 Black (069-BLK) has 21 units remaining in the Rate Contract. PO threshold is 21.	21	2026-08-22 20:19:12.526374	READ	21	2	\N	2026-08-22 20:18:55.071568	t	\N	\N	\N	\N	NORMAL
107	TENDERING_REQUIRED	2026-08-22 20:16:18.0926	URGENT: Tendering required for cartridge Canon Cartridge 069 Magenta (069-MAG). Store availability: 0, Rate contract availability: 0, Combined availability: 0. Tendering threshold: 10. Combined availability is below the tendering threshold.	0	2026-08-22 20:25:29.218295	READ	10	4	\N	2026-08-22 20:16:22.900548	t	0	0	0	10	URGENT
106	PROCUREMENT_THRESHOLD	2026-08-22 20:16:13.314413	Procurement Alert: Canon Cartridge 069 Magenta (069-MAG) has 0 units remaining in the Rate Contract. PO threshold is 10.	0	2026-08-22 20:25:29.218295	READ	10	4	\N	2026-08-22 20:16:18.081601	t	\N	\N	\N	\N	NORMAL
115	TENDERING_REQUIRED	2026-08-24 22:40:33.806365	URGENT: Tendering required for cartridge Canon Cartridge 069 Black (069-BLK). Store availability: 0, Rate contract availability: 21, Combined availability: 21. Tendering threshold: 25. Combined availability is below the tendering threshold.	21	\N	UNREAD	25	2	\N	2026-08-24 22:40:39.324975	t	21	21	0	25	URGENT
\.


--
-- TOC entry 5006 (class 0 OID 17799)
-- Dependencies: 222
-- Data for Name: rate_contracts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rate_contracts (id, contract_date, created_at, net_available_quantity, quantity_already_executed, quantity_taken_through_wo, rate_per_unit, supplier_name, tax_percentage, total_contract_quantity, updated_at, cartridge_id) FROM stdin;
7	2026-08-13	2026-08-13 16:39:46.495847	450	0	50	5000.00	Rajesh	18.00	500	2026-08-13 16:41:02.681603	1
8	2026-08-13	2026-08-13 23:16:49.435386	80	0	40	8500.00	M/s HP India Sales Pvt Ltd	18.00	120	2026-08-13 23:16:49.780582	1
10	2026-08-18	2026-08-18 12:50:05.287101	21	0	0	2323.00	raj	18.00	21	2026-08-18 12:50:05.287101	2
11	2026-08-18	2026-08-18 12:54:09.902125	90	0	0	3000.00	Sambhav	18.00	90	2026-08-18 12:54:09.902125	11
6	2026-08-13	2026-08-13 16:22:35.928667	40	0	460	5000.00	Sagar Varshney	18.00	500	2026-08-18 13:01:35.788159	1
12	2026-08-20	2026-08-20 07:03:02.995118	400	0	100	5000.00	XYZ	18.00	500	2026-08-20 07:03:33.24691	1
2	2026-08-13	2026-08-13 15:47:58.476439	69	1	30	4500.00	M/s Canon India Pvt Ltd	18.00	100	2026-08-20 07:38:24.603223	1
5	2026-08-13	2026-08-13 16:12:40.764077	47	3	143	3000.00	Anjali Varshney	18.00	193	2026-08-20 07:42:00.927074	6
9	2026-08-17	2026-08-17 12:12:17.131005	800	100	100	7000.00	Raghav	18.00	1000	2026-08-20 07:58:02.255329	18
3	2026-08-13	2026-08-13 15:55:33.048904	97	3	0	4500.00	M/s Canon India Pvt Ltd	18.00	100	2026-08-20 08:26:55.442545	1
1	2026-08-13	2026-08-13 15:43:19.634056	39	1	60	4500.00	M/s Canon India Pvt Ltd	18.00	100	2026-08-20 08:37:05.961354	1
4	2026-08-13	2026-08-13 16:09:24.760414	68	2	30	4500.00	M/s Canon India Pvt Ltd	18.00	100	2026-08-20 08:37:11.586172	1
13	2026-08-20	2026-08-20 08:40:13.708478	1000	0	0	899.90	QWE	18.00	1000	2026-08-20 08:40:13.708478	5
14	2026-08-20	2026-08-20 11:21:06.890272	3408	592	1000	9000.00	Neeraj	18.00	5000	2026-08-20 12:17:23.581512	10
15	2026-08-20	2026-08-20 12:32:21.441103	9000	0	1000	49999.86	Ajay Devgn	18.00	10000	2026-08-20 12:33:30.607091	16
16	2026-08-20	2026-08-20 13:13:27.485565	12000	0	0	4000.00	Kajol Devgn	18.00	12000	2026-08-20 13:13:27.485565	14
17	2026-08-20	2026-08-20 14:31:03.238507	7000	0	2000	900.00	Alia	18.00	9000	2026-08-20 14:37:58.400211	18
18	2026-08-20	2026-08-20 14:39:27.137446	14000	0	1000	6000.00	Ranbir	18.00	15000	2026-08-20 14:39:52.303957	5
19	2026-08-20	2026-08-20 16:02:46.101034	20000	0	0	1000.00	Rinku	18.00	20000	2026-08-20 16:02:46.101034	18
20	2026-08-20	2026-08-20 16:06:44.788583	21000	0	0	900.00	Santosh	18.00	21000	2026-08-20 16:06:44.788583	3
21	2026-08-20	2026-08-20 16:08:46.175405	5000	0	100	500.00	Rohan	18.00	5100	2026-08-20 16:09:27.832133	15
22	2026-08-20	2026-08-20 22:38:51.771837	1400	0	100	199.82	Shyam	18.00	1500	2026-08-20 22:39:40.927862	7
23	2026-08-20	2026-08-20 22:39:20.847896	1800	0	200	300.00	Ram	18.00	2000	2026-08-20 22:40:02.526527	7
\.


--
-- TOC entry 5014 (class 0 OID 18088)
-- Dependencies: 230
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, department, email, employee_id, full_name, location, password, role, status, updated_at, username) FROM stdin;
1	2026-08-18 23:37:51.730622	Procurement	anjali.varshney@iocl.co.in	IOCL10025	Anjali Varshney	Refinery	$2a$12$TcwtkhIBB2mwDG.kw8wEUO.mc2Y/8XDm.Rr1XQgLSAI/VZr9KnuDW	USER	ACTIVE	2026-08-18 23:37:51.730622	anjali.varshney
2	2026-08-18 23:46:21.586368	IT	sagarvarshney904@gmail.com	IOCL1005	Sagar Varshney	Depot	$2a$12$rT8B4AlzdbJIo2EcgDIrg.PEx7Ur0tK/WNhnC.ihlbssa9C20WTHm	USER	ACTIVE	2026-08-18 23:46:21.586368	sagar.varshney
3	2026-08-19 12:13:30.99275	Operations	arun.sharma@iocl.co.in	EMP001	Arun Sharma	Refinery	$2a$12$Oy4VJeazpM923Dfm4veYce0SS8nXwgVQG7yIue3Q2iSCZleStqBa6	USER	ACTIVE	2026-08-19 12:13:30.99275	arun001
4	2026-08-19 12:13:31.908687	Finance	bhavna.patel@iocl.co.in	EMP002	Bhavna Patel	Head Office	$2a$12$Wnlr1c6BoMc1GMbY0CS7fu2lL.b5Zm3l2nsxWxkfc9OozSQnNdGLi	USER	ACTIVE	2026-08-19 12:13:31.908687	bhavna002
5	2026-08-20 07:17:24.010113	Engineering	rahul.engineer@iocl.co.in	ENG101	Rahul Sharma	Head Office	$2a$12$djS/QHp81x7eNCCQtiOtKOqm9AR8YD7aqWMaFzeF.wNRhvNyfzc1G	USER	ACTIVE	2026-08-20 07:17:24.010113	rahul.engineer
6	2026-08-20 08:24:35.072025	Engineering	rahul.sharma@iocl.co.in	ENG1001	Rahul Sharma	Refinery	$2a$12$rcmNZ5tkJkLq9WkNOeDIL.VjozZV4.u8R8zpAh.EKaXN2sZDlORva	USER	ACTIVE	2026-08-20 08:24:35.072025	rahul.sharma
7	2026-08-20 08:25:07.390703	Engineering	engineer_5148@iocl.co.in	ENG5148	Rahul Sharma	Refinery	$2a$12$5KHGd/RGEX0.EtJvThPi3uB19SDkBF4mhncyHSGl7G5iNp4GTuMvm	USER	ACTIVE	2026-08-20 08:25:07.390703	engineer_5148
8	2026-08-20 08:25:44.627581	Engineering	engineer_4990@iocl.co.in	ENG4990	Rahul Sharma	Refinery	$2a$12$XSYFfowWxH05nZhu1XPK5./MHL7Ya/gZqFQ.afxlQqTybJ.D5o18K	USER	ACTIVE	2026-08-20 08:25:44.627581	engineer_4990
9	2026-08-20 08:26:54.858158	Engineering	engineer_4328@iocl.co.in	ENG4328	Rahul Sharma	Refinery	$2a$12$s.GCgg5hAYHwfqEGtemIguGgNjzz44cPHPPXeLJpfZOezfYvRXs3O	USER	ACTIVE	2026-08-20 08:26:54.858158	engineer_4328
10	2026-08-20 08:27:01.061158	Maintenance	pooja_5299@iocl.co.in	ENG5299	Pooja Verma	Refinery	$2a$12$OJXWJnHmN.FFWngBkY3SIO6yqM/YlQy7YuRWjU/rvx./hdbFaVKKe	USER	ACTIVE	2026-08-20 08:27:01.061158	engineer_other_5299
11	2026-08-20 08:37:05.161766	Engineering	eng_2539@iocl.co.in	ENG2539	Saurabh Engineer	Refinery	$2a$12$EwcuiKuw4PIcqVUQsSeNWunylbAvnIFndCzstmPMbDtH3ytPmtDye	USER	ACTIVE	2026-08-20 08:37:05.161766	eng_2539
12	2026-08-20 08:38:06.972546	Operations	vikram.singh@iocl.co.in	EMP202	Vikram Singh	Refinery	$2a$12$VotozhQivibTn0ItZFS4w.ZCUjwFPQ6/s2GJxAjntfMsMtvblj.tK	USER	ACTIVE	2026-08-20 08:38:06.972546	vikram.singh
13	2026-08-20 08:38:07.370836	Finance	priya.sharma@iocl.co.in	EMP203	Priya Sharma	Head Office	$2a$12$Yhn8AKRh4.b1NXG2yxTQoOUwqef99ougCyy70KydNcQUlNk1Kpj9y	USER	ACTIVE	2026-08-20 08:38:07.370836	priya.sharma
14	2026-08-20 08:38:07.731178	Maintenance	rajesh.patel@iocl.co.in	EMP204	Rajesh Patel	Terminal	$2a$12$9YcfiXoJm/S1g9/XnCTQhu9L3xOVcnsoZx4Jz8f/bOMYVHIrpN84m	USER	ACTIVE	2026-08-20 08:38:07.731178	rajesh.patel
15	2026-08-20 08:38:08.079668	Procurement	amit.kumar@iocl.co.in	EMP205	Amit Kumar	Head Office	$2a$12$l2qUTowh0zt0MkoZ6/IIkOeGGhf7Lz4dROZrCTMF0SnQV/tOnVmpu	USER	ACTIVE	2026-08-20 08:38:08.079668	amit.kumar
16	2026-08-20 08:38:08.4329	Stores	sunita.rao@iocl.co.in	EMP206	Sunita Rao	Depot	$2a$12$jgclFqZPpXhoudgNTaKj7uA8XTS2vQldsjLdXHLx83I0C5aLvW5Yu	USER	ACTIVE	2026-08-20 08:38:08.433796	sunita.rao
17	2026-08-20 08:38:08.796889	Engineering	manoj.tiwari@iocl.co.in	EMP207	Manoj Tiwari	Refinery	$2a$12$TB2Zq9QrKzlzcg8crmq.Y.SQ.jl8yFYZtp1.nlrEjBfCT3F1/NQpi	USER	ACTIVE	2026-08-20 08:38:08.796889	manoj.tiwari
18	2026-08-20 08:38:09.171344	Human Resources	kavita.nair@iocl.co.in	EMP208	Kavita Nair	Regional Office	$2a$12$CaXrsIzNlrsfnd6KAIVOLuavedOH4WSVRrmRtu3r7d333T6so.rnu	USER	ACTIVE	2026-08-20 08:38:09.171344	kavita.nair
19	2026-08-21 13:05:41.379293	IT	live.engineer.test@iocl.co.in	ENG888	Live Test Engineer	Refinery	$2a$12$Iup3QPZ2hhCp/dEgKqnEIOdXp/yFzzkwjq2HVL8ICrUK7Qoz0GZoC	USER	ACTIVE	2026-08-21 13:05:41.379293	live.engineer.test
20	2026-08-21 13:14:09.41546	IT	dev.engineer@iocl.co.in	ENG555	Dev Engineer	Refinery	$2a$12$SGUafmMbomQ.5vh2NUTbZ.BH2OCLq19St5I1DboeEkXrw12x.VpsK	USER	ACTIVE	2026-08-21 13:14:09.41546	dev.engineer
21	2026-08-22 19:59:41.10871	Operations	saurabh@gmail.com	Saurabhtest	Saurabh	Head Office	$2a$12$0gLz.evjzFMQFqcspZWP0OsVS5/0NTvPnhupCWfvFYtDMWuo5LSs6	USER	ACTIVE	2026-08-22 19:59:41.10871	Saurabhtest
22	2026-08-22 20:02:44.764999	Engineering	ehgwqk@g.com	egdiwedhe	gcsjdq	Other	$2a$12$cSw8w/5wkW2BCR6ZjVK/ouNNdZtg8hjGgdP48xMqCaMi68/AKlZUi	USER	ACTIVE	2026-08-22 20:02:44.764999	ABC_
\.


--
-- TOC entry 5025 (class 0 OID 0)
-- Dependencies: 215
-- Name: admins_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admins_id_seq', 1, true);


--
-- TOC entry 5026 (class 0 OID 0)
-- Dependencies: 231
-- Name: asset_usages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asset_usages_id_seq', 20, true);


--
-- TOC entry 5027 (class 0 OID 0)
-- Dependencies: 227
-- Name: assets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assets_id_seq', 7, true);


--
-- TOC entry 5028 (class 0 OID 0)
-- Dependencies: 217
-- Name: call_up_purchase_orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.call_up_purchase_orders_id_seq', 24, true);


--
-- TOC entry 5029 (class 0 OID 0)
-- Dependencies: 223
-- Name: cartridge_thresholds_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cartridge_thresholds_id_seq', 18, true);


--
-- TOC entry 5030 (class 0 OID 0)
-- Dependencies: 219
-- Name: cartridges_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cartridges_id_seq', 18, true);


--
-- TOC entry 5031 (class 0 OID 0)
-- Dependencies: 233
-- Name: employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employees_id_seq', 25, true);


--
-- TOC entry 5032 (class 0 OID 0)
-- Dependencies: 225
-- Name: procurement_alerts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.procurement_alerts_id_seq', 115, true);


--
-- TOC entry 5033 (class 0 OID 0)
-- Dependencies: 221
-- Name: rate_contracts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rate_contracts_id_seq', 23, true);


--
-- TOC entry 5034 (class 0 OID 0)
-- Dependencies: 229
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 22, true);


--
-- TOC entry 4800 (class 2606 OID 17779)
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--
-- TOC entry 4832 (class 2606 OID 18142)
-- Name: asset_usages asset_usages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asset_usages
    ADD CONSTRAINT asset_usages_pkey PRIMARY KEY (id);


--
-- TOC entry 4820 (class 2606 OID 17932)
-- Name: assets assets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);


--
-- TOC entry 4804 (class 2606 OID 17789)
-- Name: call_up_purchase_orders call_up_purchase_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_up_purchase_orders
    ADD CONSTRAINT call_up_purchase_orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4814 (class 2606 OID 17823)
-- Name: cartridge_thresholds cartridge_thresholds_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cartridge_thresholds
    ADD CONSTRAINT cartridge_thresholds_pkey PRIMARY KEY (id);


--
-- TOC entry 4808 (class 2606 OID 17797)
-- Name: cartridges cartridges_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cartridges
    ADD CONSTRAINT cartridges_pkey PRIMARY KEY (id);


--
-- TOC entry 4840 (class 2606 OID 18528)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- TOC entry 4845 (class 2606 OID 18546)
-- Name: employees idx_employee_number; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT idx_employee_number UNIQUE (employee_number);


--
-- TOC entry 4818 (class 2606 OID 17833)
-- Name: procurement_alerts procurement_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.procurement_alerts
    ADD CONSTRAINT procurement_alerts_pkey PRIMARY KEY (id);


--
-- TOC entry 4812 (class 2606 OID 17803)
-- Name: rate_contracts rate_contracts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rate_contracts
    ADD CONSTRAINT rate_contracts_pkey PRIMARY KEY (id);


--
-- TOC entry 4806 (class 2606 OID 17805)
-- Name: call_up_purchase_orders uk30cjsjq3gp7s8pjwvc4yep86j; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_up_purchase_orders
    ADD CONSTRAINT uk30cjsjq3gp7s8pjwvc4yep86j UNIQUE (po_number);


--
-- TOC entry 4802 (class 2606 OID 17781)
-- Name: admins uk47bvqemyk6vlm0w7crc3opdd4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT uk47bvqemyk6vlm0w7crc3opdd4 UNIQUE (email);


--
-- TOC entry 4810 (class 2606 OID 17807)
-- Name: cartridges uk57es3lfdvj0tki8thxm79r1vb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cartridges
    ADD CONSTRAINT uk57es3lfdvj0tki8thxm79r1vb UNIQUE (part_number);


--
-- TOC entry 4824 (class 2606 OID 18098)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4822 (class 2606 OID 17934)
-- Name: assets uk_assets_serial_number; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT uk_assets_serial_number UNIQUE (serial_number);


--
-- TOC entry 4826 (class 2606 OID 18100)
-- Name: users ukd1s31g1a7ilra77m65xmka3ei; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukd1s31g1a7ilra77m65xmka3ei UNIQUE (employee_id);


--
-- TOC entry 4816 (class 2606 OID 17835)
-- Name: cartridge_thresholds ukjfgbufo5j1cjdvqfo2wh2j05i; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cartridge_thresholds
    ADD CONSTRAINT ukjfgbufo5j1cjdvqfo2wh2j05i UNIQUE (cartridge_id);


--
-- TOC entry 4828 (class 2606 OID 18102)
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 4830 (class 2606 OID 18096)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4833 (class 1259 OID 18144)
-- Name: idx_asset_usage_asset_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_asset_usage_asset_id ON public.asset_usages USING btree (asset_id);


--
-- TOC entry 4834 (class 1259 OID 18268)
-- Name: idx_asset_usage_beneficiary_emp_no; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_asset_usage_beneficiary_emp_no ON public.asset_usages USING btree (beneficiary_employee_no);


--
-- TOC entry 4835 (class 1259 OID 18145)
-- Name: idx_asset_usage_cartridge_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_asset_usage_cartridge_id ON public.asset_usages USING btree (cartridge_id);


--
-- TOC entry 4836 (class 1259 OID 18146)
-- Name: idx_asset_usage_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_asset_usage_date ON public.asset_usages USING btree (usage_date);


--
-- TOC entry 4837 (class 1259 OID 18269)
-- Name: idx_asset_usage_dept; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_asset_usage_dept ON public.asset_usages USING btree (beneficiary_department);


--
-- TOC entry 4838 (class 1259 OID 18143)
-- Name: idx_asset_usage_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_asset_usage_user_id ON public.asset_usages USING btree (user_id);


--
-- TOC entry 4841 (class 1259 OID 18531)
-- Name: idx_employee_department; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_employee_department ON public.employees USING btree (department);


--
-- TOC entry 4842 (class 1259 OID 18533)
-- Name: idx_employee_location; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_employee_location ON public.employees USING btree (location);


--
-- TOC entry 4843 (class 1259 OID 18530)
-- Name: idx_employee_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_employee_name ON public.employees USING btree (full_name);


--
-- TOC entry 4846 (class 1259 OID 18532)
-- Name: idx_employee_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_employee_status ON public.employees USING btree (status);


--
-- TOC entry 4847 (class 1259 OID 18529)
-- Name: uk_employees_employee_number; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uk_employees_employee_number ON public.employees USING btree (employee_number);


--
-- TOC entry 4849 (class 2606 OID 17813)
-- Name: rate_contracts fk9taq5kwp2epx924im6eb8nx3t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rate_contracts
    ADD CONSTRAINT fk9taq5kwp2epx924im6eb8nx3t FOREIGN KEY (cartridge_id) REFERENCES public.cartridges(id);


--
-- TOC entry 4848 (class 2606 OID 17808)
-- Name: call_up_purchase_orders fkac0pqe38jftptocyintv2wd4k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.call_up_purchase_orders
    ADD CONSTRAINT fkac0pqe38jftptocyintv2wd4k FOREIGN KEY (rate_contract_id) REFERENCES public.rate_contracts(id);


--
-- TOC entry 4853 (class 2606 OID 18147)
-- Name: asset_usages fkf4dsg43xjmgo4hefkjiyqir1x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asset_usages
    ADD CONSTRAINT fkf4dsg43xjmgo4hefkjiyqir1x FOREIGN KEY (asset_id) REFERENCES public.assets(id);


--
-- TOC entry 4854 (class 2606 OID 18157)
-- Name: asset_usages fkgfdqtum44u9qesue9d3god8o5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asset_usages
    ADD CONSTRAINT fkgfdqtum44u9qesue9d3god8o5 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4852 (class 2606 OID 17935)
-- Name: assets fkgr89x876jjl7sbs3mhnd7rh7t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT fkgr89x876jjl7sbs3mhnd7rh7t FOREIGN KEY (cartridge_id) REFERENCES public.cartridges(id);


--
-- TOC entry 4850 (class 2606 OID 17836)
-- Name: cartridge_thresholds fkkklvwci3xigrq6j64jb70pk95; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cartridge_thresholds
    ADD CONSTRAINT fkkklvwci3xigrq6j64jb70pk95 FOREIGN KEY (cartridge_id) REFERENCES public.cartridges(id);


--
-- TOC entry 4851 (class 2606 OID 17841)
-- Name: procurement_alerts fkp03fcvalkls1y6x0t8nkp65bc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.procurement_alerts
    ADD CONSTRAINT fkp03fcvalkls1y6x0t8nkp65bc FOREIGN KEY (cartridge_id) REFERENCES public.cartridges(id);


--
-- TOC entry 4855 (class 2606 OID 18152)
-- Name: asset_usages fksrbyoy2j00d5ahj4rgrjggiuq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asset_usages
    ADD CONSTRAINT fksrbyoy2j00d5ahj4rgrjggiuq FOREIGN KEY (cartridge_id) REFERENCES public.cartridges(id);


-- Completed on 2026-08-24 23:11:39

--
-- PostgreSQL database dump complete
--

\unrestrict lGXHAFZ6U9Wk3zWhtz10qINyrdmXTLfze4c5iDyih0FzL8dvAPdP3Bnrsn3gPwA

